### ISSUE TITLE
aku ada issue ngan hng

### ISSUE THREAD

**Issue by FlyingTrowel** [Sirazulhaq-Abdul-Majid/Malinja-Reservation-System#3]
aku dah lama x puas hati ngan hng zul
![IMG-20210706-WA0024](https://user-images.githubusercontent.com/89365242/174733570-175df1ba-7547-46b7-8bcd-7de6d6c96edb.jpg)
.

**Comment by Sirazulhaq-Abdul-Majid** [comment]
gitgudscrub
